python3 main.py test_case0_fast.json 20
python3 main.py test_case0_reno.json 20
python3 main.py test_case1_fast.json 20
python3 main.py test_case1_reno.json 20
python3 main.py test_case2_fast.json 70
python3 main.py test_case2_reno.json 70
python3 main.py test_case3.json 20
python3 main.py test_case4.json 20
python3 main.py test_case5_fast.json 30
python3 main.py test_case5_reno.json 30
python3 main.py test_case_custom.json 20
